---
deployment:
  tasks:
    - export DEPLOYPATH=/home/techno/public_html/admin
    - cd $DEPLOYPATH
    - php artisan storage:link
    - php artisan config:clear
    - php artisan cache:clear
    - php artisan view:clear
    - php artisan migrate --force